<a href="https://colab.research.google.com/github/patroswastik/HRV-Based-Cardiac-Arrest/blob/main/HRV_Based_Cardiac_Arrest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing Libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import MinMaxScaler,StandardScaler,PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Flatten
from tensorflow.keras.optimizers import Adam
from keras.utils import np_utils

In [ ]:
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/HRV.csv')

In [ ]:
df

SBP        DBP    Mean HR  ...     AppEN    SampEN  Result
0     128.845712  88.722778  85.123808  ...  0.446175  1.069270       1
1     127.927398  87.670022  87.486723  ...  0.386453  1.060359       1
2     126.919674  86.092977  83.179963  ...  0.516678  1.092024       1
3     123.902447  87.665186  84.027245  ...  0.349478  1.110636       1
4     125.780293  83.292150  88.043730  ...  0.653466  1.063307       1
...          ...        ...        ...  ...       ...       ...     ...
1557  122.909077  83.119585  88.488837  ...  0.623226  1.167634       0
1558  127.292700  87.788509  85.848941  ...  0.779002  1.149087       0
1559  124.685823  86.890732  82.765324  ...  0.572941  1.122830       0
1560  113.450000  66.160000  70.920000  ...  0.812340  1.134560       1
1561  125.972514  82.687400  89.117099  ...  0.600624  1.387486       0

[1562 rows x 20 columns]

In [ ]:
X = df.drop(['Result'],axis=1)
y = df['Result']

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=1)

# Logistic Regression

In [ ]:
lr = LogisticRegression()

In [ ]:
lr.fit(X_train,Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
lr.score(X_test,Y_test)

0.9041533546325878

# Decision Tree Classifier

In [ ]:
dr = DecisionTreeClassifier()

In [ ]:
dr.fit(X_train,Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
dr.score(X_test,Y_test)

0.8881789137380192

# Neural Network

In [ ]:
sc = StandardScaler()

In [ ]:
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(500,input_dim=19,activation="relu"))
model.add(Dense(400,activation="relu"))
model.add(Dense(300,activation="relu"))
model.add(Dense(200,activation="relu"))
model.add(Dense(100,activation="relu"))
model.add(Dense(50,activation="relu"))
model.add(Dense(1,activation="sigmoid"))

In [ ]:
model.compile(optimizer="adam",loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
history = model.fit(X_train,Y_train,epochs=20,validation_split=0.2)

Train on 999 samples, validate on 250 samples
Epoch 1/20
999/999 [==============================] - 0s 254us/sample - loss: 0.0210 - acc: 0.9920 - val_loss: 0.7663 - val_acc: 0.9240
Epoch 2/20
999/999 [==============================] - 0s 259us/sample - loss: 0.0188 - acc: 0.9940 - val_loss: 0.7398 - val_acc: 0.9160
Epoch 3/20
999/999 [==============================] - 0s 239us/sample - loss: 0.0140 - acc: 0.9970 - val_loss: 0.9162 - val_acc: 0.8840
Epoch 4/20
999/999 [==============================] - 0s 234us/sample - loss: 0.0201 - acc: 0.9940 - val_loss: 0.7794 - val_acc: 0.9200
Epoch 5/20
999/999 [==============================] - 0s 241us/sample - loss: 0.0088 - acc: 0.9970 - val_loss: 0.9118 - val_acc: 0.9240
Epoch 6/20
999/999 [==============================] - 0s 242us/sample - loss: 0.0154 - acc: 0.9960 - val_loss: 0.8666 - val_acc: 0.9240
Epoch 7/20
999/999 [==============================] - 0s 239us/sample - loss: 0.0033 - acc: 0.9980 - val_loss: 0.8912 - val_acc: 0.9280
Ep

In [ ]:
score = model.evaluate(X_test,Y_test)

313/313 [==============================] - 0s 112us/sample - loss: 0.7978 - acc: 0.9169


In [ ]:
x = sc.fit_transform(X)
pred = model.predict(x)
pred.round()

array([[1.],
       [1.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)

In [ ]:
# plt.scatter(range(313),y)
# plt.scatter(range(313),pred.round())

In [ ]:
confusion_matrix(y,pred.round())

array([[734,  17],
       [ 26, 785]])

In [ ]:
confusion_matrix(y,lr.predict(X))

array([[683,  68],
       [ 83, 728]])

In [ ]:
confusion_matrix(y,dr.predict(X))

array([[732,  19],
       [ 16, 795]])